name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: staticwebsite-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
      - uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: 1.72.0
          args: --release --all-features
